### PR TITLE
Nginx https redirect not tested

### PR DESCRIPTION
**Pull request by 1ma**
Sister PR to #18, contains the changes to the nginx configurations that "should" work but haven't been tested live yet.

### CODE REVIEW

**Comment by twofaktor** [comment]
* Delete file `security.md`, `ride-the-lightning.md` & `blockchain-explorer.md` are already merged on PR #18 
* `web-app.md` already tested and working fine, ready to merge.
* The rest have not been tested and probably will not be tested short term.

**Comment by twofaktor** [comment]
Delete `web-app.md` already merged on https://github.com/twofaktor/minibolt/commit/4a1de872c0ab9e9c19cb41719664e22566683e65

**Comment by 1ma** [comment]
Done :+1:

**Comment by 1ma** [comment]
Closed in favor of #28

**Pull request closed without merging**
